---
- name: dependency provisioning
  hosts: all
  strategy: free
  gather_facts: false
  tasks:
    - name: apt-get update
      raw: apt-get -y update
    - name: install python
      raw: apt-get -y install python-minimal
