---
- name: deploy update to pipeline microservice
  hosts: all
  become: yes
  serial: 1
  tasks:
    
    - name: stop pipeline microservice
      systemd:
        name: treetracker-pipeline-microservice
        state: stopped

    - name: remove microservice api directory
      file:
        state: absent
        path: ~/treetracker-pipeline-microservice

    - name: ensure directory exists
      file:
        path: ~/treetracker-pipeline-microservice
        state: directory

    - name: copy pipeline microservice
      unarchive:
        src: ../../build/treetracker-pipeline-microservice.tar.gz
        dest: ~/treetracker-pipeline-microservice

    - name: copy config into place
      copy:
        src: ../../../config/{{ env }}/pipeline-microservice/config.js
        dest: ~/treetracker-pipeline-microservice/config/config.js
        decrypt: yes

    - name: restart pipeline microservice
      systemd:
        name: treetracker-pipeline-microservice
        enabled: true
        state: restarted
